# Remplace ces 2 valeurs par celles affichées par SonarCloud lors de l'import du projet
# (sonarcloud.io > + > Analyze new project) - voir
# docs/deployment/10-qualite-securite-code.md#102-sonarqube-via-sonarcloud-pas-dhébergement-à-gérer
sonar.projectKey=TON_ORG_SONARCLOUD_hr-frontend
sonar.organization=TON_ORG_SONARCLOUD

sonar.sources=src
sonar.exclusions=**/*.test.ts,**/*.test.tsx,dist/**
