apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hr-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abdessalemAttiaEsprit/HumanEdge.git
    targetRevision: main
    path: infra/k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: hr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
