apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - sealed-secret.yaml

patchesStrategicMerge:
  - patch-configmap.yaml

images:
  - name: docker.io/CHANGE_ME/hr-backend
    newName: docker.io/abdessalem123/hr-backend
    newTag: latest
  - name: docker.io/CHANGE_ME/hr-frontend
    newName: docker.io/abdessalem123/hr-frontend
    newTag: latest
